API_HOST_URL: 'https://learn.crink.ink'
ENVIRONMENT_DISPLAY_NAME: 'CRINK'
PLATFORM_NAME: 'CRINK'
PLATFORM_DESTINATION_NAME: 'www.crink.ink'
FEEDBACK_EMAIL_ADDRESS: 'sruthi@crink.ink'
COURSE_SHARING_ENABLED : true
DISCUSSIONS_ENABLED : true
PUSH_NOTIFICATIONS : true
USER_PROFILES_ENABLED : true
VIDEO_TRANSCRIPT_ENABLED: true
DOWNLOAD_TO_SD_CARD_ENABLED: true
COURSE_DATES_ENABLED: false
TAB_LAYOUTS_ENABLED: true
ANNOUNCEMENTS_ENABLED: true
WHATS_NEW_ENABLED: false
COURSE_VIDEOS_ENABLED: false
YOUTUBE_PLAYER:
  ENABLED: true
  API_KEY: 'AIzaSyC0QvxzB6h5zh1oo3m1Gt4b7u6dX1PPmxuA'
DISCOVERY :
  COURSE:
    TYPE : 'native'
NEW_LOGISTRATION_ENABLED : true
CERTIFICATES_ENABLED : true

